### ISSUE TITLE
Support for ES2015 Map/Set

### ISSUE THREAD

**Issue by mjackson** [ljharb/is-equal#1]
Hey @ljharb!

From a quick scan of the source code, it doesn't look like you currently support ES2015 Map and/or Set objects (please correct me if I'm wrong) and I was wondering if you have any plans there. I'm currently using [deep-equal](https://github.com/substack/node-deep-equal) to do equality comparisons in [expect](https://github.com/mjackson/expect), but [it doesn't look like they're keen to support them](https://github.com/substack/node-deep-equal/issues/28) because they are only interested in comparing public API. But I thought you might be interested in supporting them since you're going for "conceptual equality".

Also, does this library work well with circular references?

If you do, I think I could possibly make the switch and close these two issues :)

https://github.com/mjackson/expect/issues/47
https://github.com/mjackson/expect/issues/50

Thanks!

**Comment by ljharb** [comment]
I definitely don't currently support it - you can `Array.from`/spread them to arrays, and compare them that way, and it should work great (assuming none of the keys/values are also collections), but I definitely should add support for generic iterables. It will require an additional dependency, but I don't think that's problematic.

As for circular references, I'm not really sure, but probably not - if you can file another issue referencing https://github.com/mjackson/expect/issues/50 I can discuss/tackle that separately.

**Comment by ljharb** [comment]
Published as v1.3.0.
