### ISSUE TITLE
Support for circular references

### ISSUE THREAD

**Issue by mjackson** [ljharb/is-equal#2]
This issue is a follow-up on #1.

It would be nice to be able to test for equality with objects that contain circular references. See https://github.com/mjackson/expect/issues/50 for an instance of where this would be useful.

**Comment by ljharb** [comment]
This appears to already work - I'm sure there's some edge cases that it won't work for, but the case you provided does work.

**Comment by ljharb** [comment]
This was fixed by https://github.com/ljharb/is-equal/commit/2517c2151d57451f7f7009df065bf1601316ee46, but that change introduced an unintentional breaking change, so it was reverted in https://github.com/ljharb/is-equal/commit/ccb8a3edd7a181258df4bba577d0164d1da76ace.

**Comment by ljharb** [comment]
I've restored basic circular reference support, but note that there will likely be edge cases (PRs welcome). The only true way to handle this would be using a `Map` (and a fallback for < ES6) to track any seen value, where the map key was the value and the map value was a Set of things determined to be equal to it.

It's pretty complex so I'd prefer not to have to do it without compelling use cases.

**Comment by ljharb** [comment]
Released as `v1.4.0`
