### ISSUE TITLE
Don't check for [[Prototype]] equality

### ISSUE THREAD

**Issue by mjackson** [ljharb/is-equal#22]
IMO `Object.create(null)` and `{}` are *conceptually* equal. i.e. both are empty objects. I've run into this issue a few times this week.

The first was when I was upgrading `then-redis` to use the latest `redis`, which [recently switched](https://github.com/NodeRedis/node_redis/commit/228573b8d78c7bb3d00c28413093422428b27325) to using `Object.create(null)` as the prototype for objects returned from `HGETALL` operations. Some of my tests were doing `expect(result).toEqual({ some: 'stuff' })`.

The second case was earlier today when I was trying to upgrade `expect` to use the latest `query-string` (see https://github.com/mjackson/history/pull/268). Like `redis`, they [recently switched](https://github.com/sindresorhus/query-string/commit/7bebd8e430eb41ed42a749a1dd1d546eeb7fedb5) to returning an `Object.create(null)` from a `parse` of an empty query string.

Anyway, one of the main reasons I was attracted to using `is-equal` to power equality assertions in `expect` was because the project description says this library checks for *conceptual* equality, not exact. Conceptually, both `Object.create(null)` and `{}` are both empty objects. And in both of the practical instances I've mentioned above that's how `Object.create(null)` is being used.

**Comment by mjackson** [comment]
I guess the other way I could do this would be to iterate over objects in `toEqual` and compare their values. Similar to how we discussed handling `Set` and `Map` in https://github.com/mjackson/expect/issues/93.

**Comment by ljharb** [comment]
imo a normal object and a null object aren't conceptually equal tho - one is an empty object, one is an empty dict.

**Comment by mjackson** [comment]
@ljharb That's fine. It's easy enough for me to get the kind of behavior that I want in `expect` by just [wrapping](https://github.com/mjackson/expect/blob/e352755314bbd9eb96c7ea415e414426bf7e31a2/modules/TestUtils.js#L9) `is-equal` to get the kind of loose equality I'm looking for.

**Comment by ljharb** [comment]
Sounds good.

Another way to determine equality would be to compare `new Map(Object.entries(x))` for both `x`, once you're comparing Maps in an unordered fashion.
