### ISSUE TITLE
Failing expect build in Safari and IE

### ISSUE THREAD

**Issue by mjackson** [ljharb/is-equal#3]
I'm not 100% sure this is an is-equal bug, but it seems like it.

The expect build is failing in Safari and IE. See https://travis-ci.org/mjackson/expect/builds/96101892

It looks like the stack traces originate from inside is-equal. Would you mind taking a look, @ljharb?

**Comment by ljharb** [comment]
Sure - I'll look into this today.

https://github.com/mjackson/expect/blob/master/modules/__tests__/toEqual-test.js#L32-L35 appears to be one of the failing tests.

I suspect this is because Map/Set in Safari 8 can only be iterated by `for..of` - I'll probably have to use a technique like https://github.com/ljharb/map-tojson/blob/master/index.js#L9-L28 for that, which is pretty ugly.

IE 9 - 11 I'm not sure, but I'll look into that today also.

**Comment by ljharb** [comment]
OK so. In Safari 8, `Symbol.iterator` does not exist - `Map` and `Set` do, but the *only* way they are iterable is with `for..of` or their `forEach` method. I'll have to add some fallback code to handle that case.

**Comment by mjackson** [comment]
Hmm, I wonder if that's the case in IE as well.

**Comment by ljharb** [comment]
IE 11 seems to pass with my Safari 8 fix. Pushing up soon.

**Comment by ellbee** [comment]
I am seeing a breakage in the `redux` build (which uses `expect`). It seems to be due to object key order.

```js
var isEqual = require('is-equal')

var a = {a: 1, b: 2, c: 3}
var b = {a: 1, c: 3, b: 2}

console.log(isEqual(a,b))  // prints false
```

**Comment by mjackson** [comment]
Ah, sorry @ellbee. I may have made the switch to is-equal prematurely. Can you please open an issue on `expect` and reference this one?

**Comment by ellbee** [comment]
No worries, will do.

**Comment by ljharb** [comment]
Also please file a separate issue here - I think https://github.com/ljharb/is-equal/commit/2517c2151d57451f7f7009df065bf1601316ee46 broke this, by causing object key ordering to start mattering. I'll fix that ASAP also.

**Comment by ljharb** [comment]
@ellbee @mjackson the ordering thing was an unintentional breaking change; I've reverted that and `v1.3.1` will be published that fixes that (as well as this issue)

**Comment by ellbee** [comment]
Great, thank you.

**Comment by mjackson** [comment]
:tada: Thanks for the quick turnaround here, @ljharb! I've updated expect to use is-equal 1.4.0. Here's to a bright future making testing better :)

**Comment by ljharb** [comment]
\\( ﾟ◡ﾟ)/ please file any issues that come up and i'll get to them asap :-)
