### ISSUE TITLE
Delegate to equals method on object if it exists

### ISSUE THREAD

**Issue by bschlenk** [ljharb/is-equal#35]
I'm using [expect](https://github.com/mjackson/expect) in my tests which uses is-equal to determine if two objects are equal. The two objects I'm comparing can be unequal from a member standpoint, but equal from a conceptual standpoint. I have defined a method `equals` on my object that compares them conceptually. 

is-equal will determine that two conceptually equal objects are unequal. I would like to be able to write `expect(object1).toEqual(object2);`, but instead I have to write `expect(object1.equals(object2)).toBeTruthy();`. This doesn't produce a useful error message since it only talks about boolean values. 

It would be nice if `is-equal` would delegate to an existing `equals` method if it existed. Different conventions might exist for the name of such a method, so maybe something like a global method within `is-equal` that could be called before running tests to set the name of an equals method if there is one.

**Comment by ljharb** [comment]
The problem with introducing a convention like that is that no such convention exists in JavaScript.

I think it would be very surprising to people if their "equals" method suddenly got called by `is-equal`, especially if nothing else in JS used that convention for comparison.

One possibility - although it would only work in environments with native Symbols, which kind of makes it a nonstarter - is that `is-equal` could export a special Symbol value, and then check for *that*.

**Comment by ljharb** [comment]
Making `is-equal` stateful is a clever solution to letting each individual app determine what the property key for their "equals" method is, but a) I don't want to make a pure function stateful, and b) what happens if you're comparing objects from two modules that use different names for their equality function?

**Comment by bschlenk** [comment]
These are good points. I did find a workaround within expect, which is to define a custom assertion: 

```javascript
expect.extend({
  toBeClassEqual(other) {
    expect.assert(
      this.actual.equals(other),
      'expected %s to be equal to %s',
      this.actual.toString(), other.toString()
    );
    return this;
  }
});
```

I do like the symbol idea, but it would take a while for it to be supported everywhere. This can be closed.

**Comment by ljharb** [comment]
A custom matcher seems the most appropriate, pending something being added to the language.
