### ISSUE TITLE
Set and Map only works in order

### ISSUE THREAD

**Issue by BridgeAR** [ljharb/is-equal#42]
Right now a equal set with elements not in order are considered to be unequal. But a set and map in general is not sorted and should work in what ever order.
```js
const a = new Set([1, 2])
const b = new Set([2, 1])
equal(a, b) // false
```

**Comment by ljharb** [comment]
In fact both Set and Map are ordered in JS, so the behavior is correct.

**Comment by BridgeAR** [comment]
Ok, you are correct about that but isn't it the intention of a Set to be be handled as unordered? Especially because:
```js
a.has(1) && a.has(2) === b.has(1) && b.has(2)
```

**Comment by ljharb** [comment]
No, that's not the intention, otherwise `.forEach` and Symbol.iterator wouldn't iterate in order.

It's reasonable to want to compre Sets and Maps as if they're unordered, of course, but that's not what this package does.

**Comment by refack** [comment]
[a bit off topic]
@ljharb why is it like that? (the spec, not this package)?

**Comment by ljharb** [comment]
@refack if ordering isn't tightly specified, then implementations can and will implement whatever ordering they want - we already dealt with that problem with object key ordering.

If iteration is possible via any means (such that ordering is apparent), then the ordering has to be deterministic in the spec.
