### ISSUE TITLE
Object.create(null) is not equal to {}—Feature or bug?

### ISSUE THREAD

**Issue by IonicaBizau** [ljharb/is-equal#43]
Seems like a bug to me:

```js
isEqual({}, {}) // → true
isEqual(Object.create(null), Object.create(null)) // → true

// Would expect true, as well
isEqual({}, Object.create(null)) // → false
isEqual(Object.create(null), {}) // → false
```

The use-case is that `querystring.parse` returns an object created with `Object.create(null)`. And in my test I've been using `{}`.

**Comment by IonicaBizau** [comment]
And the output in `expect` is weird, too:

![screen shot 2017-08-20 at 17 49 18](https://user-images.githubusercontent.com/2864371/29495841-f4c4725e-85cf-11e7-8d64-d4abb7a6acc6.png)

**Comment by ljharb** [comment]
They're indeed different, because their [[Prototype]] is different.

For the output in expect, you'd need to file an issue there - but if you're using {} in your test, and comparing to a null object, it should be failing.

**Comment by IonicaBizau** [comment]
The output is the same in all JS consoles I have tried (Node, browsers).
I opened an issue in `expect`: https://github.com/mjackson/expect/issues/225

Thanks!
